---
version: "3.9"
services:
  nutcracker:
    platform: linux/amd64
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      dockerfile: Dockerfile-dev
    restart: unless-stopped
    ports:
      - 6380:6380

  redis:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: redis:7.2
    ports:
      - "6379:6379"
